[package]
name = "host"
version = "0.1.0"
edition = "2024"

[dependencies]
capture = { path = "../../crates/capture" }
encoder = { path = "../../crates/encoder" }
protocol = { path = "../../crates/protocol" }
transport = { path = "../../crates/transport" }
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "time",
] }